"""Redaktionelle Rassedaten; Quellen am Ende jeder erzeugten Rasseseite."""
BREEDS = []
def add(slug, name, group, origin, short, history, appearance, colors, nature, use, fact, sources):
    BREEDS.append(dict(slug=slug,name=name,group=group,origin=origin,short=short,history=history,appearance=appearance,colors=colors,nature=nature,use=use,fact=fact,sources=sources))

add('ayam-cemani','Ayam Cemani','Großhuhn','Indonesien','Außergewöhnliche schwarze Pigmentierung und grünlich glänzendes Gefieder.','','','','','','',[])
add('zwerg-new-hampshire','Zwerg-New-Hampshire','Zwerghuhn','Deutschland','Ein ruhiges Nutzzwerghuhn mit goldbraunem oder weißem Federkleid.',
'Die Zwerg-New-Hampshire wurden in Deutschland nach dem Vorbild der amerikanischen Großrasse entwickelt. Mehrere Züchter arbeiteten an einer kleinen Form, die deren wirtschaftliche Eigenschaften bewahren sollte. Der goldbraune Farbenschlag wurde 1961 anerkannt.',
'Der Körper ist kräftig und gut gerundet. Eine breite Brust und der entwickelte Bauch lassen den Nutztyp erkennen. Auf dem Kopf sitzt ein aufrechter Einfachkamm, also ein einzelner gezackter Kamm.',
'Gezüchtet werden goldbraune und weiße Tiere. Beim goldbraunen Hahn bilden die warmen Töne von Hals und Körper einen deutlichen Gegensatz zu den dunklen Schwanzfedern.',
'Die Rasse wird als ruhig und gesellig beschrieben. Sie gilt als frühreif und robust. Wie zutraulich einzelne Tiere werden, hängt auch von Aufzucht und Umgang ab.',
'Im Mittelpunkt standen Eier und eine brauchbare Fleischleistung im kleinen Format. Die Hennen legen braunschalige Eier. Brutlust kann vorkommen, ist aber nicht bei jeder Henne ausgeprägt.',
'Der amerikanische Name bezeichnet die Großrasse; die hier vorgestellte Zwergform ist eine deutsche Züchtung.',
 [('Wikipedia: Zwerg-New Hampshire','https://de.wikipedia.org/wiki/Zwerg-New_Hampshire')])
add('zwerg-cochin','Zwerg-Cochin','Zwerghuhn','China','Rundliche Urzwerge mit weichem Gefieder und befiederten Füßen.',
'Zwerg-Cochin stammen aus China und wurden in Europa zunächst auch Peking-Bantam genannt. Sie gehören zu den Urzwergen: Ihre Geschichte ist eigenständig und nicht einfach die Verkleinerung der großen Cochin.',
'Das üppige, weiche Gefieder lässt den tief stehenden Körper rund erscheinen. Auch die Läufe und Zehen tragen Federn. Der kleine Einfachkamm hebt sich deutlich vom federreichen Körper ab.',
'Die Rasse wird in vielen Farben und Zeichnungen gezüchtet. Neben glatten Federn gibt es eine gelockte Variante, bei der sich die Federn nach außen biegen. Beide zeigen denselben rundlichen Grundtyp.',
'Zwerg-Cochin können ausgesprochen zutraulich werden. Die Hennen gelten als zuverlässige Glucken. Wegen der tiefen Stellung und Fußfedern sind trockene, saubere Aufenthaltsbereiche besonders wichtig.',
'Ihre Bedeutung liegt vor allem in der Liebhaber- und Ausstellungszucht. Die Erhaltung des charakteristischen Typs und der Farbvielfalt steht stärker im Vordergrund als eine hohe Eierleistung.',
'Obwohl große Cochin ähnlich aussehen, sind Zwerg-Cochin keine bloße Miniaturausgabe dieser Rasse.',
[('Wikipedia: Zwerg-Cochin','https://de.wikipedia.org/wiki/Zwerg-Cochin'),('Zwerg-Cochin Klub Schweiz: Geschichte','https://zwerg-cochin.ch/geschichte.shtml')])
add('altenglische-zwerg-kaempfer','Altenglische Zwerg-Kämpfer','Zwerghuhn','England','Kleine, bewegliche Hühner mit straffem Gefieder und lebhaftem Auftreten.',
'Die Rasse entstand in England. Ihre Entwicklung verbindet verschiedene kleine Hühner mit dem Erscheinungsbild alter englischer Kampfhühner. Die genaue Zusammensetzung der Ausgangsrassen lässt sich nicht vollständig rekonstruieren. In Deutschland wurden sie zu Beginn des 20. Jahrhunderts bekannt.',
'Kennzeichnend sind ein kurzer, fester Körper und knapp anliegende Federn mit wenig Flaum. Die klar erkennbare Muskulatur und die bewegliche Haltung unterscheiden sie von rundlichen, stark befiederten Zwerghühnern.',
'Es gibt zahlreiche Farbenschläge. Dazu zählen schwarze und gesperberte Tiere. Farbe und Zeichnung verändern den optischen Eindruck, der kompakte, straffe Körperbau bleibt jedoch das gemeinsame Erkennungsmerkmal.',
'Die Tiere gelten als lebhaft, mutig und gegenüber vertrauten Menschen häufig sehr zutraulich. Ihr aufmerksames Verhalten fällt auch beim ruhigen Beobachten im Ausstellungskäfig auf.',
'Heute werden sie als Rasse- und Ausstellungsgeflügel gehalten. Ihr Name bewahrt die Verbindung zum historischen Kämpfertyp; das Zuchtinteresse gilt dem Erscheinungsbild und der Vitalität.',
'Trotz des kämpferischen Namens beschreibt der Zwergkämpfer-Club die Bindung an den vertrauten Pfleger als besonders eng.',
[('Zwergkämpfer-Club: Rasseporträt beim KTZV Kramsach (PDF)','https://www.kleintierzuchtverein-t11-kramsach.at/attachments/File/Altenglische_Zwergk__mpfer.pdf')])
add('zwerg-barnevelder','Zwerg-Barnevelder','Zwerghuhn','Deutschland','Braune Eier und eine auffällige doppelte Federzeichnung.',
'Die Großrasse trägt den Namen des niederländischen Ortes Barneveld. Ihre Zwergform wurde in Deutschland entwickelt. Zu den Ausgangstieren gehörten kleine Barnevelder und andere Zwergrassen. Die braun-schwarzdoppeltgesäumten Zwerge wurden 1931 anerkannt.',
'Ein kräftiger, abgerundeter Körper und eine breite Brust prägen das Erscheinungsbild. Der aufrechte Einfachkamm und die unbefiederten Beine lassen den typischen Hühnerumriss gut erkennen.',
'Besonders bekannt ist die doppelte Säumung: Auf den Körperfedern der Henne verlaufen dunkle Linien innerhalb und am Rand der braunen Federfläche. Daneben bestehen weitere Farben, darunter schwarze und weiße Tiere.',
'Der Sonderverein beschreibt Barnevelder als zutraulich. Bei ruhigem Umgang sind sie deshalb auch für Besucher gut zu beobachten. Individuelles Verhalten und Gewöhnung bleiben dabei entscheidend.',
'Die Zucht verbindet ein ansprechendes Federkleid mit der Nutzung als Eierlieferant. Braune Eier gehören zu den geschätzten Merkmalen; die Schalenfarbe allein reicht jedoch nicht zur Bestimmung einer Rasse.',
'„Doppeltgesäumt“ meint zwei dunkle Zeichnungslinien auf einer Feder, nicht zwei übereinanderliegende Federn.',
[('Sonderverein: Herauszüchtung','https://www.sv-barnevelder.de/herausz%C3%BCchtung'),('Sonderverein: Rasseüberblick','https://www.sv-barnevelder.de/'),('GZV Eilendorf: Zwerg-Barnevelder','https://www.gzveilendorf.de/zwerg-barnevelder/')])
add('marans','Marans','Großhuhn','Frankreich','Kräftige französische Hühner, bekannt für dunkelbraune Eier.',
'Marans entstanden im Westen Frankreichs rund um die Stadt gleichen Namens und die Region La Rochelle. Lokale Landhühner wurden mit weiteren Rassen gekreuzt. Dabei entwickelte sich ein Nutztyp, bei dem dunkle, große Eier besondere Bedeutung erhielten.',
'Die Tiere besitzen einen breiten, tiefen Rumpf und eine volle Brust. Sie sollen kräftig, aber beweglich wirken. Zu dem in Deutschland beschriebenen Typ gehören leicht befiederte Läufe und ein Einfachkamm.',
'Bekannt ist etwa schwarz-kupfer: Dunkles Körpergefieder trifft auf kupferfarbene Partien am Hals, beim Hahn auch in weiteren Schmuckfedern. Es gibt außerdem andere Farbenschläge, etwa gesperbert und weiß.',
'Der Marans-Club beschreibt die Rasse als ruhig und robust. Das kräftige Aussehen bedeutet nicht, dass die Tiere schwerfällig sind. Sie nutzen gerne Bewegungsmöglichkeiten und Beschäftigung im Auslauf.',
'Marans sind Nutz- und Ausstellungshühner. Bei der Zucht zählt neben Form und Gefieder vor allem die braune Eierschale. Die Farbtiefe kann zwischen Hennen und im Verlauf der Legezeit unterschiedlich ausfallen.',
'Bei dieser Rasse ist auch das Ei ein wichtiges Zuchtmerkmal – ein schön gezeichneter Vogel allein erfüllt noch nicht alle Zuchtziele.',
[('Marans-Club Deutschland: Die Marans','https://www.marans-club.de/alles-uber-marans/'),('Marans-Club: Musterbeschreibung (PDF)','https://www.marans-club.de/wp-content/uploads/go-x/u/734a5c47-628b-4d2d-8965-8fe7cd281c38/Musterbeschreibung-Marans-Stand-2012.pdf'),('Wikipedia: Marans','https://de.wikipedia.org/wiki/Marans_%28Huhn%29')])
add('deutsches-reichshuhn','Deutsches Reichshuhn','Großhuhn','Deutschland','Ein traditionsreiches Zweinutzungshuhn mit rechteckiger Körperform.',
'Das Deutsche Reichshuhn entstand zu Beginn des 20. Jahrhunderts aus der Idee eines leistungsfähigen deutschen Wirtschaftshuhns. Dafür wurden verschiedene bereits bestehende Rassen kombiniert. Der historische Name gehört zur Entstehungszeit der Rasse.',
'Der Rumpf erscheint von der Seite länglich und rechteckig. Rücken und Bauch verlaufen annähernd parallel. Ein feiner Rosenkamm sitzt flach auf dem Kopf; die hellen Läufe sind unbefiedert.',
'Das Gefieder liegt straff an und lässt die Körperform deutlich erkennen. Es gibt mehrere Farbenschläge, unter anderem weiß, schwarz, rot und gestreift. Die Form ist ein gemeinsames Merkmal über diese Farbvarianten hinweg.',
'Die Rasse gilt als robust und zutraulich. Ihre Eigenschaften passen zur traditionellen Haltung mit Auslauf, in dem die Tiere Bewegung und Möglichkeiten zur Futtersuche erhalten.',
'Als Zweinutzungshuhn sollte sie sowohl Eier als auch Fleisch liefern. Heute ist neben diesen Nutzeigenschaften die Erhaltung einer traditionsreichen Rasse ein wesentliches Anliegen der Züchter.',
'Der Ausdruck „Backsteinform“ beschreibt anschaulich das längliche Rechteck des Körpers – er meint keine plumpe oder unbewegliche Haltung.',
[('VIEH: Deutsches Reichshuhn','https://www.vieh-ev.de/Rassen/Gefluegel/reichshuhn.html'),('Wikipedia: Deutsches Reichshuhn','https://de.wikipedia.org/wiki/Deutsches_Reichshuhn')])
add('orientalische-roller','Orientalische Roller','Taube','Kleinasien / Zentralasien','Eine Tümmlertaube mit besonderer Schwanzhaltung und Flugtradition.',
'Orientalische Roller sind eine Taubenrasse. Der Sonderverein führt ihre Herkunft auf Kleinasien und zentralasiatische Gebiete zurück. Über verschiedene Länder gelangten sie nach Mitteleuropa. Ihre Zuchtgeschichte ist eng mit der Freude an besonderen Flugbewegungen verbunden.',
'Die Taube wirkt gedrungen und besitzt einen auffälligen, angehobenen Schwanz. Die Flügel werden unter dem Schwanz getragen. Diese Kombination verleiht ihr eine unverwechselbare Silhouette.',
'Die Rasse wird in verschiedenen Farben und Zeichnungen gezüchtet. Für das Erkennen des Typs sind neben der Farbe vor allem Körperhaltung, Flügellage und Schwanz wichtig.',
'Orientalische Roller werden als gut züchtende Tauben beschrieben. Als domestizierte Tauben leben sie in Paarbeziehungen und benötigen eine auf Tauben abgestimmte Unterbringung und Betreuung.',
'Die ursprüngliche Bedeutung liegt im Kunstflug. Als „Rollen“ werden überschlagartige Bewegungen im Flug bezeichnet. Bei einem Ausstellungstier lässt sich die individuelle Flugleistung aus dem Aussehen allein nicht ableiten.',
'Orientalische Roller besitzen häufig mehr Schwanzfedern als die üblichen zwölf vieler anderer Tauben. Die Bürzeldrüse fehlt oder ist nur schwach entwickelt.',
[('SV Orientalischer Roller: Unsere Rasse','https://sv-orientalischer-roller.de/unsere-rasse/')])
add('bielefelder-kennhuehner','Bielefelder Kennhühner','Großhuhn','Deutschland','Große, ruhige Hühner mit bereits bei Küken erkennbaren Geschlechtsunterschieden.',
'Die Bielefelder Kennhühner wurden von Gerd Roth entwickelt und in den 1970er Jahren vorgestellt. Das Zuchtziel verband wirtschaftliche Eigenschaften mit der Möglichkeit, männliche und weibliche Küken anhand ihrer Flaumzeichnung zu unterscheiden.',
'Der kräftige, gestreckte Körper zeigt einen langen Rücken und eine breite Brust. Ein Einfachkamm, unbefiederte Läufe und die insgesamt stattliche Erscheinung prägen den Nutztyp.',
'Die Farbenschläge heißen kennsperber und silber-kennsperber. Bei kennsperber verbindet sich eine warme Grundfärbung mit einer helleren Sperberzeichnung. Die silberne Variante zeigt entsprechend kühlere Farbtöne.',
'Bielefelder gelten als ruhige, robuste Hühner. Sie nutzen Auslauf und können sich bei regelmäßiger, behutsamer Betreuung gut an Menschen gewöhnen. Rassebeschreibungen ersetzen dabei nicht die Beobachtung des einzelnen Tieres.',
'Sie gehören zu den Zweinutzungsrassen: Eier und Fleisch waren beide Teil des Zuchtziels. Die Eier sind braun und können gesprenkelt sein. Für Liebhaber kommt der Erhalt der kennfarbigen Zeichnung hinzu.',
'„Kennhuhn“ bezieht sich auf das Erkennen des Geschlechts am Kükenflaum. Hahn und Henne unterscheiden sich also schon lange vor der Ausbildung großer Kämme.',
[('Naturhistorisches Museum Mainz: Steckbrief (PDF)','https://www.mainz.de/microsite/naturhistorisches-museum/medien/bindata/Steckbrief_Bielefelder-Kennhuhn.pdf'),('Sonderverein Bielefelder Kennhühner','https://bielefelder-kennhuhn.de/'),('Wikipedia: Bielefelder Kennhuhn','https://de.wikipedia.org/wiki/Bielefelder_Kennhuhn')])
add('bielefelder-zwerg-kennhuehner','Bielefelder Zwerg-Kennhühner','Zwerghuhn','Deutschland','Kennfarbige Nutzzwerge mit langem Rücken und zutraulichem Wesen.',
'Die Bielefelder Zwerg-Kennhühner wurden in Deutschland als kleine Form des Kennhuhntyps entwickelt. Auch hier stand die Verbindung von Nutzwert und früh erkennbaren Geschlechtsunterschieden im Mittelpunkt. Ihre Entwicklung gehört in die jüngere Geschichte der Rassegeflügelzucht.',
'Der Körper ist gestreckt, der Rücken lang und gerade. Der Schwanz steigt in einem flachen Übergang an. Die Tiere stehen nicht hochbeinig; die Schenkel treten nur wenig hervor.',
'Gezüchtet werden kennsperber und silber-kennsperber. Die kennsperberfarbigen Tiere verbinden warme Brauntöne mit einer hellgrauen Sperberung. Hahn und Henne unterscheiden sich in Farbe und Zeichnung.',
'Der betreuende Sonderverein beschreibt die Rasse als zutraulich und wetterhart. Sie gehört zu den schnell wachsenden Nutzzwerghühnern. Ihr Wesen entfaltet sich besonders bei ruhigem, regelmäßigem Umgang.',
'Die Hennen legen braune Eier. Neben dieser Nutzung werden die Körperform und die kennfarbige Zeichnung erhalten. Die Zwergform besitzt einen eigenen Rassetyp und ist nicht einfach ein zufällig klein gebliebenes Großhuhn.',
'Die männlichen Küken erscheinen heller, während weibliche Küken deutlichere dunkle Rückenstreifen zeigen. Darauf beruht die Kennfarbigkeit.',
[('Sonderverein: Die Rasse','https://www.sv-bielefelder-zwergkennhuehner.de/die-rasse'),('RGZV Hagen: Bielefelder Zwerg-Kennhühner','https://rgzv-hagen-westfalen.com/Rassen-im-Verein/Zwerg-Bielefelder-Kennhuehner/')])
add('zwerg-sussex','Zwerg-Sussex','Zwerghuhn','England / Deutschland','Ruhige Zwerghühner mit breitem Stand und rechteckigem Profil.',
'Die Großrasse Sussex stammt aus England. Die Entwicklung ihrer Zwergform wird England und Deutschland zugeordnet. Kleine Tiere der Großrasse und weitere Zwerghühner trugen dazu bei, den kräftigen Nutztyp im kleineren Format zu erhalten.',
'Zwerg-Sussex zeigen einen breiten, mittelhohen Stand und einen rechteckig wirkenden Körper. Brust und Bauch sind gut entwickelt. Der Kopf trägt einen Einfachkamm, die Läufe sind unbefiedert.',
'Sehr bekannt ist weiß-schwarzcolumbia: Auf heller Grundfarbe liegen schwarze Zeichnungspartien besonders an Hals und Schwanz. Daneben gibt es weitere Varianten, etwa gelb-schwarzcolumbia und braun-porzellanfarbig.',
'Das ruhige Wesen gehört zu den geschätzten Eigenschaften. Viele Tiere werden bei behutsamem Umgang zutraulich. Sie bleiben dennoch aktive Hühner, die scharren, Futter suchen und ihre Umgebung erkunden.',
'Die Zwergform verbindet Liebhaberzucht mit einer nutzbaren Eierleistung. Die Schalen sind gelblich bis hellbraun. Auch Brutverhalten kann auftreten; nicht jede Henne entwickelt es in gleicher Weise.',
'„Columbia“ bezeichnet hier eine Verteilung der Gefiederzeichnung. Es ist keine Angabe über das Herkunftsland der Rasse.',
[('Sonderverein Sussex: Beschreibung','https://sussex-sv.de/beschreibung/'),('Zootier-Lexikon: Zwerghuhnrassen','https://www.zootier-lexikon.org/voegel-aves/huehnervoegel-und-hoatzins/fasanenartige/haushuhn-zwergrassen')])
add('zwerg-phoenix','Zwerg-Phönix','Zwerghuhn','Deutschland','Schlanke Langschwanzhühner mit fließender Rückenlinie.',
'Zwerg-Phönix gehören zur europäischen Zuchtgeschichte japanisch geprägter Langschwanzhühner. Die Phönixzucht entwickelte sich unter Verwendung japanischer Ausgangstiere in Deutschland weiter; daraus entstand auch die kleine Form.',
'Die Tiere sind schlank und tragen den lang gestreckten Körper fast waagerecht. Besonders der Hahn besitzt lange, schmale Schmuckfedern an Hals, Sattel und Schwanz. Der Rücken geht fließend in den langen Schwanz über.',
'Zu den Farbenschlägen gehören unter anderem goldhalsig, silberhalsig, weiß und schwarz. Kleine weiße Ohrscheiben und ein kleiner Einfachkamm ergänzen die elegante Erscheinung.',
'Die Rasse wirkt aufmerksam und beweglich. Ihr langes Gefieder braucht eine entsprechend eingerichtete, saubere Umgebung, damit Federn nicht ständig verschmutzen oder beschädigt werden.',
'Bei dieser Liebhaberrasse stehen die besondere Form und das Schmuckgefieder im Vordergrund. Eine möglichst hohe Eierleistung war für die Ausprägung des Langschwanztyps nicht das maßgebende Zuchtziel.',
'Auch die Hennen besitzen einen auffällig langen Schwanz. Ihre oberen Schwanzdeckfedern können säbelartig gebogen sein.',
[('Sonderverein: Zwerg-Phönix','https://www.sv-phoenix-onagadori.de/rassen/zwerg-phoenix/'),('BDRG: Phönix, Zwerg-Phönix und Onagadori','https://www.bdrg.de/fuer-sie/rasse-des-jahres/dresdner-zwerg-dresdner-rasse-des-jahres-2025-im-bdrg-1')])
add('chabo','Chabo','Zwerghuhn','Japan','Japanische Urzwerge mit kurzem Rücken und steil getragenem Schwanz.',
'Chabo sind eine alte japanische Zwerghuhnrasse. In Japan wurde ihr besonderer Erscheinungstyp gepflegt, bevor sie auch in Europa Liebhaber fanden. Sie gehören zu den Urzwergen und besitzen keine entsprechende Großrasse.',
'Der Körper ist gedrungen, der Rücken kurz und der Schwanz steil aufgerichtet. Die großen Kopfpunkte fallen im Verhältnis zur kleinen Gestalt auf. Typisch sind kurze Beine; in der Zucht gibt es auch langbeinige Varianten.',
'Chabo werden in vielen Farben gehalten. Zusätzlich unterscheiden sich die Federstrukturen: Es gibt glatte, gelockte und seidenfiedrige Tiere. Diese Unterschiede beeinflussen auch, wie gut ein Tier fliegen kann.',
'Der Chabo-Club beschreibt sie als ruhig und zutraulich. Hennen können hingebungsvolle Glucken sein. Trotz ihrer kleinen Gestalt brauchen sie Bewegung, Beschäftigung und geschützte Rückzugsmöglichkeiten.',
'Chabo werden vor allem aus Freude an ihrer Form, ihrem Verhalten und ihrer Vielfalt gezüchtet. Die Erhaltung dieses besonderen Zwerghuhntyps steht im Vordergrund.',
'Ein Chabo ist kein junges oder noch nicht ausgewachsenes Großhuhn: Seine kleine Gestalt gehört zur eigenständigen Rasse.',
[('Chabo-Club: Rasse und Verein','https://chaboclub.de/'),('Chabo-Club: Häufige Fragen','https://chaboclub.de/faq/'),('BDRG: Rassen- und Farbschläge-Verzeichnis (PDF)','https://www.bdrg.de/media/user_upload/Rassenverzeichnis_BDRG_2024.pdf')])
add('zwerg-araucana','Zwerg-Araucana','Zwerghuhn','Deutschland','Schwanzlose Zwerghühner mit auffällig türkisfarbenen Eiern.',
'Zwerg-Araucana wurden in Deutschland aus dem Araucanahuhn herausgezüchtet und 1981 anerkannt. Die Großrasse ist mit Südamerika, besonders Chile, verbunden. Weiter zurückliegende Ursprungsfragen werden unterschiedlich erklärt und sind nicht sicher geklärt.',
'Kennzeichnend sind der gerundete Körper und die Schwanzlosigkeit. Am Kopf können Federbommeln, ein Bart oder eine Kombination dieser Merkmale vorkommen. Ein kleiner Erbsenkamm ergänzt das ungewöhnliche Aussehen.',
'Es gibt verschiedene Farbenschläge, darunter wildfarbige, schwarze und weiße Tiere. Die Farbe des Gefieders ist von der charakteristischen Schalenfarbe der Eier zu unterscheiden.',
'Die Rasse wird als lebhaft und vital beschrieben. Die kleinen Tiere erkunden ihre Umgebung aufmerksam. Die Ausprägung der Kopfmerkmale ist bei der Zucht ein wichtiges Unterscheidungsmerkmal.',
'Zwerg-Araucana verbinden Rassegeflügelzucht mit der Freude an türkis bis grünlich-blau gefärbten Eiern. Eine grüne Eierschale allein beweist jedoch keine Rassezugehörigkeit, denn auch Kreuzungen können grüne Eier legen.',
'Federbommeln und Bart sind unterschiedliche Merkmale: Bommeln sitzen seitlich am Kopf, während der Bart die unteren Kopfpartien befiedert.',
[('Sonderverein Araucana: Geschichte der Zwergform','https://www.sonderverein-araucana.de/'),('Wikipedia: Zwerg-Araucana','https://de.wikipedia.org/wiki/Zwerg-Araucana'),('Sonderverein: Keck und vital (PDF)','https://www.sonderverein-araucana.de/wp-content/uploads/2017/11/Zwerg-Araucanas-keck-und-vital.pdf')])
add('sundheimer','Sundheimer','Großhuhn','Deutschland','Zutrauliche Zweinutzungshühner aus der Region Kehl am Rhein.',
'Sundheimer wurden in Sundheim bei Kehl am Rhein entwickelt. Zunächst stand ein schnell wachsendes Fleischhuhn im Mittelpunkt. Später wurde die Legeleistung stärker berücksichtigt; daraus entstand der heutige Zweinutzungstyp.',
'Ein voller, breiter Rumpf und die gut entwickelte Brust prägen den Körperbau. Die Haltung ist annähernd waagerecht. Die leicht befiederten Füße gehören zu den auffälligen Merkmalen.',
'Die Zeichnung heißt weiß-schwarzcolumbia. Der Körper ist überwiegend weiß, während besonders Hals und Schwanz schwarze Partien zeigen. Hahn und Henne ähneln sich in der Verteilung dieser Zeichnung.',
'Sundheimer werden als zutraulich beschrieben. Zu ihren traditionellen Nutzeigenschaften zählen zügiges Wachstum und Frühreife. Saubere, trockene Bereiche helfen dabei, die Fußbefiederung in gutem Zustand zu halten.',
'Eier und Fleisch bilden den ursprünglichen doppelten Nutzen. Die Rasse wird auch für ihre Winterlegeleistung geschätzt. Heute bewahren Züchter mit ihr ein Stück regionaler Geflügelgeschichte.',
'Der Name verweist auf einen konkreten Ort am Oberrhein. Das heutige Sundheim ist ein Stadtteil von Kehl.',
[('GEH: Sundheimer','https://www.g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/158-sundheimer-huhn'),('2B-Ranch: Sundheimer','https://www.2b-ranch.de/our-animals/the-sundheimer')])
add('zwerg-welsumer','Zwerg-Welsumer','Zwerghuhn','Deutschland','Nutzbetonte Zwerghühner mit braunen, oft gesprenkelten Eiern.',
'Die Großrasse Welsumer stammt aus den Niederlanden. Die Zwergform wurde dagegen in Deutschland entwickelt. In die Zucht flossen neben Welsumern verschiedene Zwerghuhnrassen ein, um Nutzwert und typisches Aussehen zu verbinden.',
'Der Körper ist kräftig und walzenförmig. Eine breite Brust und ein entwickelter Bauch passen zum Nutztyp. Der Kopf trägt einen Einfachkamm; die Beine sind unbefiedert.',
'Bekannt ist die rost-rebhuhnfarbige Variante. Hahn und Henne unterscheiden sich dabei deutlich in der Verteilung warmer Brauntöne und dunkler Zeichnung. Außerdem gibt es weitere Farbenschläge, etwa orangefarbig und silberfarbig.',
'Als Nutzzwerghühner werden sie wegen ihrer Leistungsfähigkeit geschätzt. Zum Alltag gehören Bewegung und Futtersuche. Das Verhalten einzelner Tiere hängt zusätzlich von Zuchtlinie, Aufzucht und Gewöhnung ab.',
'Braune Eier mit teils dunkleren Punkten gehören zu den typischen Merkmalen. Die Zucht richtet sich sowohl auf Form und Farbe als auch auf die Nutzeigenschaften der Hennen.',
'Der niederländische Ortsname Welsum steckt im Rassenamen, obwohl die Zwergform eine deutsche Züchtung ist.',
[('Wikipedia: Zwerg-Welsumer','https://de.wikipedia.org/wiki/Zwerg-Welsumer'),('Sonderverein Welsumer','https://www.sv-welsumer.de/')])
add('deutsche-zwerg-wyandotten','Deutsche Zwerg-Wyandotten','Zwerghuhn','Deutschland','Vielseitige Nutzzwerge mit Rosenkamm und großer Farbenvielfalt.',
'Die Geschichte der Zwerg-Wyandotten führt über amerikanische und europäische Zuchten. In Deutschland wurde ein eigener Typ weiterentwickelt. Die Bezeichnung Deutsche Zwerg-Wyandotten macht diesen Unterschied zu anderen internationalen Zuchtrichtungen deutlich.',
'Der Körper ist kräftig, breit und gestreckt. Eine gerundete Rückenlinie steigt zum Schwanz hin an. Der flache Rosenkamm und die gelben, unbefiederten Läufe sind wichtige Erkennungsmerkmale.',
'Die Vielfalt reicht von einfarbigen Tieren bis zu gesäumten oder gebänderten Federn. „Gesäumt“ bedeutet, dass eine andersfarbige Linie den Federrand betont; dadurch kann das Gefieder fast schuppenartig wirken.',
'Viele Zuchten werden als ruhig beschrieben. Brutlust kann auftreten und unterscheidet sich zwischen Linien und Einzeltieren. Die zahlreichen Farben dürfen nicht darüber hinwegtäuschen, dass der gemeinsame Körperbau entscheidend bleibt.',
'Als Nutzzwerge verbinden sie Eierleistung und Körperfülle mit einem ausgeprägten Schauwert. Züchter erhalten sowohl die Farbenschläge als auch die charakteristische Form.',
'Der Zusatz „Deutsche“ hilft, den hier gezüchteten Körper- und Schwanztyp vom ursprünglichen amerikanischen Typ zu unterscheiden.',
[('Wikipedia: Zwerg-Wyandotte','https://de.wikipedia.org/wiki/Zwerg-Wyandotte'),('Landesverband Westfalen: Typenvergleich (PDF)','https://www.westfalen-lv.de/preisrichter/2024/Unterschiede-DZW-UZW.pdf'),('Kleintierzuchtverein Sallgast: Rasseporträt','https://kleintierzuchtverein-sallgast.de/rasseportrait-zwerg-wyandotten/')])
add('deutsche-zwerg-lachshuehner','Deutsche Zwerg-Lachshühner','Zwerghuhn','Deutschland','Bart, Fußfedern und fünf Zehen machen diese Zwerge unverwechselbar.',
'Deutsche Zwerg-Lachshühner wurden in Deutschland als kleine Form des Deutschen Lachshuhns erzüchtet. Die Geschichte der Großrasse ist mit französischen Faverolles und der anschließenden deutschen Weiterzucht verbunden.',
'Die Tiere zeigen einen breiten, tiefen und gestreckten Körper. Der volle Bart verdeckt die kleinen Kehllappen weitgehend. Befiederte Läufe und fünf Zehen an jedem Fuß ergänzen die besondere Erscheinung.',
'Beim lachsfarbigen Farbenschlag unterscheiden sich die Geschlechter auffällig: Die Henne trägt warme, helle Lachstöne, der Hahn zeigt stärkere Kontraste mit dunklen Partien. Der Name beschreibt somit besonders anschaulich das Kleid der Henne.',
'Die Rasse wird als beweglich und sehr zutraulich beschrieben. Trotz des vollen Gefieders soll sie nicht plump wirken. Bart und Fußfedern bleiben in einer sauberen Umgebung besser erhalten.',
'Die Zwergform bewahrt den charakteristischen Typ einer traditionellen Nutzrasse. Heute stehen neben den Eiern besonders die Liebhaberzucht und das Erhalten der ungewöhnlichen Merkmalskombination im Vordergrund.',
'Die fünfte Zehe gehört hier zum Rassemerkmal. Die meisten anderen Hühnerrassen besitzen vier Zehen an jedem Fuß.',
[('GZV Eilendorf: Deutsche Zwerg-Lachshühner','https://www.gzveilendorf.de/deutsche-zwerg-lachshuehner/'),('Hof Hüttenland: Rassebeschreibung','https://xn--hof-httenland-0ob.de/?page_id=237'),('Geflügelzeitung: Deutsche Lachshühner','https://www.gefluegelzeitung.de/gefluegelwissen/huehner/deutsche-lachshuehner/')])
add('japanische-legewachtel','Japanische Legewachtel','Wachtel','Japan / Ostasien','Kleine domestizierte Wachteln mit kompakter Gestalt und hoher Legefreude.',
'Die Japanische Legewachtel ist die domestizierte Form der Japanischen Wachtel, Coturnix japonica. Deren Wildform stammt aus Ostasien. Durch Zuchtauswahl entwickelten sich Tiere mit höherem Körpergewicht, gesteigerter Legeleistung und unterschiedlichen Gefiederfarben.',
'Der Körper ist gedrungen und rundlich, der Hals kurz und der Schwanz sehr klein. Die Flügel liegen eng an. Häufig wirken die Tiere etwas geduckt; die Hähne sind meist kleiner und schlanker als die Hennen.',
'Die wildfarbige Zeichnung verbindet braune Töne mit hellen und dunklen Mustern. Daneben werden weitere Farben gezüchtet, darunter weiße Tiere. Bei manchen Farben hilft die Brustzeichnung bei der Unterscheidung der Geschlechter.',
'Wachteln verbringen viel Zeit am Boden. Deckung und Rückzugsmöglichkeiten entsprechen ihrer bodenorientierten Lebensweise. Sie sind aufmerksam und können bei Erschrecken plötzlich auffliegen.',
'Wie der Name sagt, steht besonders die Eiererzeugung im Mittelpunkt. Daneben gibt es die Rasse- und Farbenzucht. Japanische Legewachteln sind keine kleinen Haushühner, sondern gehören zu einer anderen Vogelart.',
'Der wissenschaftliche Name Coturnix japonica unterscheidet sie auch von der Europäischen Wachtel, Coturnix coturnix.',
[('Sonderverein Japanische Legewachteln: Beschreibung','https://www.japanische-legewachteln.de/standard-1/beschreibung/')])
add('mechelner','Mechelner','Großhuhn','Belgien','Große belgische Hühner mit breitem Körper und befiederten Läufen.',
'Die Mechelner stammen aus dem Umfeld der belgischen Stadt Mechelen. Dort wurden heimische Fleischhühner mit asiatischen Rassen gekreuzt. Die Entwicklung richtete sich auf einen kräftigen, gut nutzbaren Fleischhuhntyp.',
'Der Körper ist lang, breit und tief. Eine volle Brust und kräftige Schenkel unterstreichen den Nutztyp. Die Außenseiten der Läufe sind befiedert. Auf dem Kopf sitzt ein vergleichsweise kleiner Einfachkamm.',
'Besonders bekannt sind gesperberte Mechelner: Helle und dunkle Bereiche wechseln im Gefieder und erzeugen eine unregelmäßig gestreifte Wirkung. Daneben gibt es weiße Tiere.',
'Als schwere Hühnerrasse werden Mechelner eher als ruhig beschrieben und fliegen weniger als viele leichtere Rassen. Ihr Platzbedarf richtet sich nach dem großen Körper; ausreichend Bewegungsraum bleibt wichtig.',
'Vor der Verbreitung moderner Mastlinien waren sie bedeutende Wirtschaftshühner. Auch Eier gehören zu ihrem Nutzen, doch die ausgeprägte Fleischhuhnform ist das besonders auffällige Zuchterbe.',
'Die Bezeichnung „Mechelner Kuckuck“ bezieht sich auf das gesperberte Federkleid und den belgischen Herkunftsort.',
[('GEH: Mechelner','https://g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/500-mechelner'),('Wikipedia: Mechelner','https://de.wikipedia.org/wiki/Mechelner'),('GEH: Natürliches Verhalten von Hühnern (PDF)','https://g-e-h.de/images/stories/downloadbereich/Natuerliches_Verhalten_Huehnerbroschuere_25_11_2019.pdf')])
add('westfaelische-totleger','Westfälische Totleger','Großhuhn','Deutschland','Lebhafte westfälische Landhühner mit gesprenkeltem Gefieder.',
'Westfälische Totleger gehören zu den traditionellen Landhühnern Westfalens. Ihre Geschichte ist besonders mit dem Ravensberger Hügelland und dem Teutoburger Wald verbunden. Geschätzt wurden sie als ausdauernde Eierlieferanten in bäuerlicher Haltung.',
'Der eher leichte Landhuhntyp ist auf Beweglichkeit ausgerichtet. Ein Rosenkamm liegt flach auf dem Kopf. Die Körperform wirkt deutlich schlanker als bei schweren Fleischhühnern.',
'Es gibt goldene und silberne Tiere mit dunkler Sprenkelzeichnung. Das Zusammenspiel von heller Grundfarbe und dunklen Zeichnungselementen macht die Rasse auch aus einiger Entfernung auffällig.',
'Die Tiere gelten als robust, wetterhart und eifrige Futtersucher. Weiträumige Ausläufe passen zu ihrem bewegungsfreudigen Wesen. Sie zeigen anschaulich, wie eng alte Landhuhnrassen mit ihrer früheren Haltungsform verbunden sind.',
'Der ursprüngliche Zuchtschwerpunkt lag auf der Eierleistung. Heute trägt ihre Zucht außerdem zum Erhalt regionaler Geflügelvielfalt bei. Historische Leistungsbeschreibungen sind dabei keine Garantie für jedes einzelne Tier.',
'„Totleger“ bedeutet nicht, dass sich die Hennen zu Tode legen. Der Name wird vom plattdeutschen Ausdruck für Dauerleger hergeleitet.',
[('LWL: Regionale Nutztierrassen (PDF)','https://www.geographische-kommission.lwl.org/media/filer_public/ae/7b/ae7b4699-dfc4-4407-9ada-09b8c73e6735/geko-aktuell2021_2.pdf'),('VIEH: Westfälischer Totleger','https://www.vieh-ev.de/Rassen/Gefluegel/totleger.html'),('Wikipedia: Westfälischer Totleger','https://de.wikipedia.org/wiki/Westf%C3%A4lischer_Totleger')])
