"""Die zweite Serie: eigenständige Großrassen und Antwerpener Bartzwerge.

Gewichte sind Zuchtrichtwerte, keine Sollgewichte für jedes einzelne Tier.
Die Angaben zu Bruteiern sind Mindestgewichte, keine mittleren Eigewichte.
"""
NEW_BREEDS = []

def add(slug, name, origin, short, weights, egg, history, appearance, colors,
        nature, husbandry, use, fact, sources, group='Großhuhn'):
    NEW_BREEDS.append(dict(slug=slug, name=name, origin=origin, short=short,
        group=group, weights=weights, egg=egg, history=history,
        appearance=appearance, colors=colors, nature=nature,
        husbandry=husbandry, use=use, fact=fact, sources=sources))

add('brahma', 'Brahma', 'Asien / USA',
    'Große, gelassene Hühner mit befiederten Füßen und markantem Blick.',
    ('3,5–5 kg', '3–4,5 kg'), 'Bruteier mindestens 53 g; gelbbraune Schale.',
    'Brahma verbinden asiatische Vorfahren mit amerikanischer Rassezucht. Im 19. Jahrhundert gelangten sie nach Europa und beeindruckten durch ihre Größe. Der Name klingt nach Indien, die Entwicklung der heutigen Rasse lässt sich aber nicht auf einen einzigen Herkunftsort reduzieren.',
    'Der breite, tiefe Körper steht auf kräftigen, befiederten Beinen. Über den Augen treten die Brauen deutlich hervor; zusammen mit dem kleinen Erbsenkamm entsteht ein fast strenger Gesichtsausdruck. Der Erbsenkamm besteht aus drei niedrigen, längs verlaufenden Reihen.',
    'Beispiele sind weiß-schwarzcolumbia, gelb-schwarzcolumbia und rebhuhnfarbig-gebändert. Bei der Columbiazeichnung konzentrieren sich dunkle Partien vor allem auf Hals und Schwanz. Gebänderte Federn zeigen dagegen mehrere Zeichnungslinien.',
    'Brahma gelten als ruhige, gutmütige Hühner. Ihr aufmerksamer Blick ist deshalb kein verlässlicher Hinweis auf einen kämpferischen Charakter. Vertrauter, geduldiger Umgang unterstützt ihre Zutraulichkeit.',
    'Für die schweren Tiere sind gut zugängliche Nester und niedrige, stabile Sitzplätze sinnvoll. Trockener, sauberer Boden hilft, die Fußfedern in gutem Zustand zu halten. Auch eine ruhige Rasse braucht Platz zum Scharren und Bewegen.',
    'Ursprünglich waren Größe und Fleischansatz wichtige Zuchtziele. Heute faszinieren besonders Körperform, Federzeichnung und Ausstrahlung. Die Eier wirken neben der mächtigen Henne vergleichsweise klein.',
    'Beim Betrachten lohnt ein Blick nach unten: Nicht nur die Beine, sondern auch Teile der Zehen tragen Federn.',
    [('Sonderverein: Brahma', 'https://sv-cochin-brahma-zwerg-brahma.de/Rassenbeschreibung/Brahma'),
     ('Zoo Stralsund: Brahma', 'https://zoo.stralsund.de/Der_Zoo/Tiere_im_Zoo/Tier-Lexikon/Brahma.html')])

add('orpington', 'Orpington', 'England',
    'Ein breiter, weicher Federwürfel mit englischer Geschichte.',
    ('4–4,5 kg', '3–3,5 kg'), 'Bruteier mindestens 53 g; cremefarbene Schale.',
    'William Cook entwickelte die Rasse im englischen Orpington. 1886 stellte er schwarze Tiere vor; weitere Farben folgten. Seine Züchtung sollte ein brauchbares Wirtschaftshuhn sein und zugleich auf Ausstellungen bestehen.',
    'Breite, Tiefe und Fülle bestimmen den fast würfelförmigen Körper. Weiche Federn verstärken diesen Eindruck. Der Kopf wirkt dazu relativ klein. Die Beine sind unbefiedert, verschwinden optisch aber teilweise im reichen Gefieder.',
    'Besonders bekannt sind gelbe Orpington. Daneben gibt es beispielsweise schwarze, weiße und blau-gesäumte Tiere. Entscheidend bleibt bei allen Farben der kräftige, gleichmäßig gerundete Rassetyp.',
    'Die schweren Hühner gelten als ruhig und wenig flugfreudig. Hennen können ausgeprägte Brutlust entwickeln. Ob ein Tier zutraulich wird, hängt auch von seinen Erfahrungen mit Menschen ab.',
    'Breite Durchgänge, niedrige Sitzstangen und trockene Einstreu passen zum schweren Körper. Bewegungsanreize im Auslauf sind auch für gemütliche Hühner wichtig. Nester sollten so bemessen sein, dass die Henne bequem hineingelangt.',
    'Orpington wurden für Eier und Fleisch gezüchtet. In der Liebhaberhaltung werden außerdem ihre Gluckeneigenschaften geschätzt. Eine feste jährliche Eierzahl wäre für unterschiedliche Linien und Haltungsbedingungen zu pauschal.',
    'Der Eindruck eines Federwürfels ist gewollt: Bei der Beurteilung zählt die Körperform ebenso wie die Gefiederfarbe.',
    [('Sonderverein: Standard und Farbenschläge', 'https://www.sv-orpington.de/standard-und-farbschl%C3%A4ge/'),
     ('Sonderverein: Vereins- und Rassegeschichte', 'https://www.sv-orpington.de/verein/'),
     ('BDRG: Rassetafeln Hühner (PDF)', 'https://www.bdrg.de/media/docs/Rassetafeln_Huehner.pdf')])

add('australorps', 'Australorps', 'Australien',
    'Australische Nutzhühner mit kräftiger Form und eng anliegendem Gefieder.',
    ('3–4 kg', '2,5–3 kg'), 'Bruteier mindestens 55 g; hellbraune Schale.',
    'Australische Züchter entwickelten aus Orpington ein stärker auf Wirtschaftlichkeit ausgerichtetes Huhn. Nach Stationen in anderen Ländern erreichte die Rasse 1952 Deutschland. Ihr Name erinnert an die australischen Orpington-Vorfahren.',
    'Die breite Brust, der tiefe Rumpf und der gut entwickelte Bauch zeigen den Nutztyp. Das Gefieder liegt enger an als bei Orpington. Ein aufrechter Einfachkamm und unbefiederte Beine lassen den Körperumriss deutlich hervortreten.',
    'Gezüchtet werden schwarze, weiße und blau-gesäumte Australorps. Beim schwarzen Farbenschlag kann das Gefieder im Licht grünlich glänzen. Dieser Glanz wirkt je nach Beleuchtung unterschiedlich stark.',
    'Australorps verbinden einen kräftigen Körper mit lebhaftem Verhalten. Sie sind keine unbeweglichen Schaufiguren, sondern erkunden ihre Umgebung. Ruhiger Umgang hilft beim Aufbau von Vertrauen.',
    'Ein strukturierter Auslauf mit Schatten und Scharrmöglichkeiten bietet Beschäftigung. Futter und Wasser sollten ohne Gedränge erreichbar sein. Bei kräftigen Hühnern lohnt es, neben dem dichten Federkleid auch die tatsächliche Körperkondition zu beobachten.',
    'Frühe Entwicklung und Nutzleistung waren wichtige Zuchtziele. Die Rasse verbindet Eier- und Fleischnutzung; heutige Leistungen unterscheiden sich zwischen Zuchtlinien und hängen von Alter, Jahreszeit und Versorgung ab.',
    'Orpington und Australorps sind verwandt, haben aber unterschiedliche Zuchtziele und einen sichtbar unterschiedlichen Federsitz.',
    [('Sonderverein: Musterbeschreibung', 'https://www.sv-australorps.de/Musterbeschreibung.htm')])

add('amrocks', 'Amrocks', 'USA',
    'Gestreifte Zweinutzungshühner mit gelben Beinen und ruhigem Wesen.',
    ('3–4 kg', '2,5–3 kg'), 'Bruteier mindestens 58 g; braune bis gelbbraune Schale.',
    'Amrocks gehen auf den amerikanischen Wirtschaftstyp der gestreiften Plymouth Rocks zurück. Die Zucht legte besonderen Wert auf rasches Wachstum und Nutzleistung. So entstand ein kräftiges Huhn für Eier und Fleisch.',
    'Die breite, tiefe Gestalt erinnert seitlich an eine liegende Glocke. Die Beine sind gelb und unbefiedert; auf dem Kopf sitzt ein Einfachkamm. Eng anliegende Federn lassen die stattliche Körperform erkennen.',
    'Kennzeichnend ist die dunkle und helle Querstreifung. Bei Hennen sind die dunklen Streifen breiter als die hellen. Deshalb wirken Hennen insgesamt dunkler als die Hähne, obwohl beide denselben Farbenschlag zeigen.',
    'Amrocks werden als ruhig und umgänglich beschrieben. Ihre kräftige Erscheinung schließt emsiges Futtersuchen nicht aus. Wie bei jeder Rasse sind Unterschiede zwischen einzelnen Tieren normal.',
    'Gut erreichbare Sitzplätze und genügend Platz an Futterstellen passen zu ihrem Körperbau. Ein abwechslungsreicher Auslauf lädt zum Scharren ein. Die ruhige Art ersetzt weder Beschäftigung noch eine passende Gruppenzusammensetzung.',
    'Die Rasse gehört zu den klassischen Zweinutzungshühnern. Wachstum, Körperfülle und Eierleistung sollen sich ergänzen. Die braune Schalenfarbe sagt dabei nichts über den Geschmack des Eis aus.',
    'Schon bei Küken können Kopfzeichnung und Beinfärbung Hinweise auf das Geschlecht geben. Diese Einschätzung verlangt Erfahrung und ist keine Garantie für jedes einzelne Küken.',
    [('Sonderverein: Amrocks-Standard', 'https://www.svamrocks.de/rassestandard-1/amrocks/'),
     ('GZV Eilendorf: Amrocks', 'https://www.gzveilendorf.de/amrocks/')])

add('vorwerkhuehner', 'Vorwerkhühner', 'Deutschland',
    'Goldgelber Körper, schwarzer Hals und Schwanz: ein unverwechselbarer Kontrast.',
    ('2,5–3 kg', '2–2,5 kg'), 'Bruteier mindestens 55 g; gelbliche Schale.',
    'Oskar Vorwerk begann um 1900 im Raum Hamburg mit der Entwicklung eines ansprechenden, brauchbaren Landhuhns. Das Zuchtziel verband eine markante Zeichnung mit wirtschaftlichen Eigenschaften. Der Rassename erinnert an den Züchter.',
    'Der Rumpf ist breit und kräftig, die Haltung wirkt gestreckt. Ein roter Einfachkamm und helle Ohrscheiben ergänzen das kontrastreiche Gefieder. Die unbefiederten Beine zeigen einen schieferblauen Ton.',
    'Goldgelbe Körperpartien treffen auf einen schwarzen Kopf, Hals und Schwanz. Anders als bei einer unregelmäßigen Scheckung sind die Farben bestimmten Körperbereichen zugeordnet. Beim Hahn glänzen die dunklen Schmuckfedern besonders auffällig.',
    'Vorwerkhühner gelten als robust, gutmütig und eifrig bei der Futtersuche. Sie nutzen ihren Auslauf aktiv. Zutraulichkeit entsteht dennoch durch Gewöhnung und verlässlichen Umgang.',
    'Sträucher, Schatten und lockerer Boden machen den Auslauf für die beweglichen Tiere interessant. Eine sichere Einfriedung und geschützte Rückzugsorte gehören dazu. Ruhiges Beobachten zeigt schnell, welche Bereiche die Gruppe bevorzugt.',
    'Die Rasse wurde für Eier und Fleisch entwickelt. Die GEH nennt etwa 150 Eier im Jahr als Orientierungswert. Das ist keine zugesicherte Leistung jeder Henne; insbesondere Alter und Brutpausen verändern das Ergebnis.',
    'Vorwerkhühner ähneln in der Farbverteilung den Lakenfeldern. Wo diese Weiß zeigen, fällt bei Vorwerkhühnern das warme Goldgelb auf.',
    [('GEH: Vorwerkhuhn', 'https://www.g-e-h.de/geh-gefl/vorwerkh.htm'),
     ('Zootier-Lexikon: Große Haushuhnrassen', 'https://www.zootier-lexikon.org/voegel-aves/huehnervoegel-und-hoatzins/fasanenartige/haushuhn-grosse-rassen')])

add('deutsche-sperber', 'Deutsche Sperber', 'Deutschland',
    'Lebhafte Landhühner mit wolkig wirkender Sperberzeichnung.',
    ('2,5–3 kg', '2–2,5 kg'), 'Bruteier mindestens 60 g; weiße Schale.',
    'Otto Trieloff entwickelte die Rasse um 1900 in Duisburg. Zunächst begegneten ihr andere Namen, darunter Rheinische Sperber. Seit 1917 ist die Bezeichnung Deutsche Sperber gebräuchlich. Gute Nutzleistung gehörte zum ursprünglichen Zuchtgedanken.',
    'Die mittelgroßen Landhühner wirken gestreckt und beweglich. Ein Einfachkamm und weiße Ohrscheiben setzen am Kopf Akzente. Die kräftige Form soll weder schwerfällig noch schmal erscheinen.',
    'Die Rasse wird gesperbert gezüchtet. Helle und dunkle Querzonen wirken weicher abgegrenzt als eine scharf gezeichnete Streifung. Dieser Unterschied lässt sich beim Vergleich mit Amrocks besonders gut entdecken.',
    'Die GEH beschreibt lebhafte, zutrauliche Tiere mit guter Futtersuche und wenig Brutneigung. Eine aktive Henne ist häufig unterwegs, statt lange an einem Platz zu bleiben.',
    'Vielseitig nutzbarer Auslauf kommt ihrer Bewegungsfreude entgegen. Verstecke und Sichtschutz gliedern die Fläche und geben rangniederen Tieren Ausweichmöglichkeiten. Eine sichere Umzäunung bleibt auch bei vertrauten Hühnern notwendig.',
    'Weiße Eier und eine brauchbare Fleischleistung kennzeichnen den Nutzgedanken. Rund 180 Eier jährlich nennt die GEH als Richtwert. Für einzelne Zuchten kann die tatsächlich erfasste Leistung davon abweichen.',
    '„Sperber“ bezeichnet hier die Federzeichnung. Der Name bedeutet nicht, dass diese Hühner wie Greifvögel jagen.',
    [('GEH: Deutscher Sperber', 'https://g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/149-deutscher-sperber')])

add('lakenfelder', 'Lakenfelder', 'Deutschland / Niederlande',
    'Weiße Landhühner mit schwarzem Hals und Schwanz und lebhaftem Auftreten.',
    ('1,75–2,25 kg', '1,5–2 kg'), 'Bruteier mindestens 50 g; weiße Schale.',
    'Die Geschichte der Lakenfelder verbindet den niederländischen und nordwestdeutschen Raum. In Deutschland bildete die Gegend um Dielingen am Dümmer ein Zuchtzentrum. Aus regionalen Landhühnern entwickelte sich der deutlich abgegrenzte Farbtyp.',
    'Die eher leichten Hühner wirken schlank und beweglich. Ihr gestreckter Körper trägt einen gut entwickelten Schwanz. Ein Einfachkamm und unbefiederte Beine ergänzen den klaren Umriss.',
    'Weiß am Körper steht im Gegensatz zu schwarzem Hals und Schwanz. Der Übergang soll deutlich erscheinen. Die Zeichnung ist daher etwas anderes als eine über den ganzen Körper verteilte schwarz-weiße Scheckung.',
    'Lakenfelder gelten als lebhaft und robust. Sie passen zu Menschen, die Freude am Beobachten aktiver Hühner haben. Ein ruhiger, regelmäßiger Umgang ist hilfreicher als häufiges Einfangen.',
    'Für bewegliche Landhühner sind Platz, Deckung und sichere Begrenzungen besonders sinnvoll. Unterschiedliche Auslaufbereiche regen die Futtersuche an. Auch leichte Hühner benötigen einen trockenen Stall und geschützte Ruheplätze.',
    'Historisch spielte die Eierleistung eine wichtige Rolle. Die GEH nennt etwa 160–200 Eier pro Jahr; diese Spanne ist ein Rasseorientierungswert. Heute gehört auch die Erhaltung der charakteristischen Zeichnung zum Zuchtinteresse.',
    'Der direkte Vergleich mit einem Vorwerkhuhn macht die gemeinsame Farbverteilung sichtbar – allerdings mit einer ganz anderen Körpergrundfarbe.',
    [('GEH: Lakenfelder Huhn', 'https://g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/152-lakenfelder-huhn')])

add('hamburger', 'Hamburger', 'Nordwesteuropa / England',
    'Elegante, bewegliche Hühner mit Rosenkamm und auffälligen Zeichnungen.',
    ('je nach Farbenschlag etwa 1,5–2,5 kg', 'je nach Farbenschlag etwa 1–2 kg'),
    'Weiße Eier; Größe und Gewicht unterscheiden sich zwischen Farbenschlägen.',
    'Unter dem Namen Hamburger wurden in England unterschiedliche nordwesteuropäische Landhuhntypen zusammengefasst. Ihre Geschichte ist deshalb vielfältiger, als der einzelne Ortsname vermuten lässt. Lack- und Sprenkelvarianten haben unterschiedliche Entwicklungslinien.',
    'Die Tiere zeigen eine elegante Landhuhnform mit gut entwickeltem Schwanz. Der flache Rosenkamm läuft hinten in einen Dorn aus. Weiße Ohrscheiben und schieferfarbene, unbefiederte Beine gehören zum charakteristischen Bild.',
    'Bekannt sind Silberlack und Goldlack sowie gesprenkelte Varianten. Bei Lackhühnern fallen dunkle Federtupfen auf heller Grundfarbe auf. Daneben gibt es unter anderem schwarze und weiße Tiere; nicht alle Farbenschläge sind gleich groß.',
    'Hamburger gelten als lebhaft und bewegungsfreudig. Wer ihnen beim Suchen und Erkunden zusieht, erkennt den Unterschied zu sehr schweren, ruhigeren Rassen. Geduldiger Umgang erleichtert die Gewöhnung an Menschen.',
    'Ein geräumiger, gut gesicherter Auslauf mit Deckung entspricht dem aktiven Typ. Flugmöglichkeiten sollten bei der Einfriedung berücksichtigt werden. Übersichtliche Futterstellen erleichtern die Beobachtung der einzelnen Tiere.',
    'Die weißen Eier waren ein wichtiger Grund für ihre frühere wirtschaftliche Bedeutung. Heute werden auch die elegante Form und Zeichnung geschätzt. Wegen der Unterschiede zwischen Varianten wird hier kein einheitliches Eigewicht angegeben.',
    '„Hamburger“ bedeutet nicht, dass alle Farbenschläge gemeinsam in Hamburg entstanden sind. Hinter dem Namen steht eine ganze Gruppe historischer Landhuhntypen.',
    [('BDRG: Rassetafeln Hühner (PDF)', 'https://www.bdrg.de/media/docs/Rassetafeln_Huehner.pdf'),
     ('Wikipedia: Hamburger – Geschichte und Unterschiede der Varianten', 'https://de.wikipedia.org/wiki/Hamburger_%28Huhn%29'),
     ('Wildpark Schwarze Berge: Hamburger Silberlack', 'https://www.wildpark-schwarze-berge.de/attraktion/hamburger-silberlack/')])

add('italiener', 'Italiener', 'Italien / europäische Zucht',
    'Lebhafte Legehühner mit weißen Ohrscheiben und großer Farbenvielfalt.',
    ('meist 2,25–3 kg', 'meist 1,75–2,5 kg'), 'Bruteier meist mindestens 55 g; weiße Schale. Farbenschlag beachten.',
    'Italienische Landhühner bildeten die Grundlage dieser Rasse. In der weiteren Zucht wurden Körperform, Legeleistung und zahlreiche Farbenschläge ausgearbeitet. Der Nutzgedanke blieb dabei neben den Anforderungen der Ausstellung wichtig.',
    'Ein langer, geräumiger Körper mit breiter Brust steht auf gelben, unbefiederten Beinen. Weiße bis cremefarbene Ohrscheiben kontrastieren mit dem roten Gesicht. Neben dem bekannten Einfachkamm gibt es auch rosenkämmige Italiener.',
    'Beispiele sind rebhuhnhalsig, goldfarbig, silberfarbig, schwarz, weiß und gestreift. Bei der gestreiften Variante lässt sich auf jeder Feder die helle und dunkle Querzeichnung verfolgen.',
    'Der Sonderverein beschreibt Italiener als ausgesprochen lebhaft und gewandt. Sie sind aufmerksame Hühner, die ihre Umgebung aktiv nutzen. Ein ruhiger Umgang erleichtert den Kontakt.',
    'Strukturierter Auslauf, sichere Begrenzungen und Rückzugsmöglichkeiten passen zur Beweglichkeit der Rasse. Gut verteilte Beschäftigungsmöglichkeiten verhindern, dass sich alle Tiere nur an einer Stelle sammeln. Futterversorgung und Bewegung gehören zusammen.',
    'Italiener wurden besonders als frühreife Legehühner geschätzt. Rund 190 Eier jährlich nennt der Sonderverein als Richtwert. Das ist keine feste Leistungsvorgabe für jede Henne; Linie, Alter und Haltung beeinflussen das Ergebnis.',
    'Bei einfachkämmigen Hennen darf sich der hintere Kammteil seitlich neigen. Er soll dabei das Auge nicht verdecken.',
    [('Sonderverein gestreifte Italiener: Standard und Zuchtgeschichte', 'https://sv-gestreifte-italiener.jimdofree.com/rassemerkmale/')])

add('rheinlaender', 'Rheinländer', 'Deutschland',
    'Gestreckte rheinische Nutzhühner mit flachem Rosenkamm.',
    ('2,5–3 kg', '2–2,5 kg'), 'Weiße Eier; die Leistung hängt von Zuchtlinie und Haltung ab.',
    'Die Entwicklung begann Ende des 19. Jahrhunderts mit Landhühnern aus der Eifel und französischen Le-Mans-Hühnern. 1907 wurden Rheinländer erstmals ausgestellt. Ziel war ein leistungsfähiges, widerstandsfähiges Wirtschaftshuhn.',
    'Der lange, tiefe Körper wirkt in der Seitenansicht annähernd rechteckig. Ein Rosenkamm liegt flach auf dem Kopf; helle Ohrscheiben setzen einen deutlichen Kontrast. Trotz Körperfülle sollen die Tiere beweglich bleiben.',
    'Es gibt unter anderem schwarze, weiße, rebhuhnhalsige, blau-gesäumte, gesperberte und silberhalsige Rheinländer. Die Farbe verändert den Eindruck, die gestreckte Grundform bleibt das verbindende Merkmal.',
    'Die Rasse gilt als lebhaft und bei gutem Umgang zutraulich. Brutlust ist eher wenig ausgeprägt. Ihr Nutztyp ist mit aktiver Futtersuche verbunden.',
    'Ein abwechslungsreicher Auslauf bietet Raum zum Suchen und Scharren. Deckung und mehrere gut erreichbare Versorgungsstellen helfen bei einer ruhigen Gruppenhaltung. Auch robuste Rassen brauchen trockene, zugfreie Ruhebereiche.',
    'Eier und Fleisch gehörten zum Zuchtziel. Die GEH nennt ungefähr 140–180 Eier jährlich als Orientierung. Auch die Winterlegefähigkeit wurde geschätzt; sie bedeutet jedoch keine garantierte durchgehende Legetätigkeit.',
    'Rheinländer und Niederrheiner sind verschiedene Rassen. Der ähnlich klingende Name allein reicht zur Zuordnung nicht aus.',
    [('GEH: Rheinländer', 'https://g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/508-rheinlaender'),
     ('BDRG: Rassetafeln Hühner (PDF)', 'https://www.bdrg.de/media/docs/Rassetafeln_Huehner.pdf')])

add('sachsenhuehner', 'Sachsenhühner', 'Deutschland',
    'Robuste Landhühner aus dem Erzgebirge mit kleinen Kopfpunkten.',
    ('2,5–3 kg', '2–2,5 kg'), 'Bruteier mindestens 55 g; cremefarbene bis hellbraune Schale.',
    'Sachsenhühner entstanden gegen Ende des 19. Jahrhunderts im Erzgebirge. Unterschiedliche Ausgangsrassen wurden zu einem widerstandsfähigen Nutzhuhn verbunden. Die Zucht sollte auch zu den raueren Bedingungen der Region passen.',
    'Die Tiere zeigen einen langgestreckten Körper und kleine Kopfpunkte. Der Einfachkamm steht aufrecht, die Kehllappen bleiben verhältnismäßig kurz. Helle Ohrscheiben setzen sich vom roten Gesicht ab.',
    'Schwarz, weiß, gesperbert und gelb gehören zu den Farbenschlägen. Die Federn lassen die Landhuhnform erkennen. Bei schwarzen Tieren fällt je nach Licht ein Glanz im Gefieder auf.',
    'Die GEH beschreibt Sachsenhühner als ruhige, frühreife und gute Futtersucher. Ruhe und Aktivität schließen sich dabei nicht aus: Im Auslauf sind sie mit Suchen und Scharren beschäftigt.',
    'Trockene Einstreu, geschützte Ruheplätze und Bewegungsraum bleiben auch bei einer wetterharten Rasse wichtig. Ein gegliederter Auslauf bietet Beschäftigung. Kleine Kopfpunkte sind kein Ersatz für einen geeigneten Stall.',
    'Die Rasse verbindet Eier- und Fleischnutzung. Als jährliche Orientierung werden etwa 120–160 Eier genannt. Für die Erhaltungszucht zählen daneben Vitalität und der charakteristische Rassetyp.',
    'Die kleinen Kämme und Kehllappen passen zur Entstehung in einer kühleren Region: Weit vorstehende Kopfteile waren dort weniger erwünscht.',
    [('GEH: Sachsenhuhn', 'https://g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/155-sachsenhuhn')])

add('ramelsloher', 'Ramelsloher', 'Deutschland',
    'Norddeutsche Landhühner mit auffallend blauen Beinen und Schnäbeln.',
    ('2,5–3 kg', '2–2,5 kg'), 'Bruteier mindestens 56 g; weiße bis cremefarbene Schale.',
    'Die Rasse entstand um 1870 in Ramelsloh südlich von Hamburg. Vierländer Landhühner wurden mit weiteren Rassen kombiniert. Die Entwicklung war eng mit der regionalen Geflügelhaltung und ihrer wirtschaftlichen Nutzung verbunden.',
    'Kräftige Landhuhnform und ein Einfachkamm prägen die Gestalt. Besonders auffällig sind schieferblaue Beine und Schnabel sowie dunkle Augen. Diese Merkmale setzen einen ungewöhnlichen Akzent zum hellen Federkleid.',
    'Ramelsloher werden weiß und gelb gezüchtet. Die einfarbigen Federn lenken den Blick auf Körperform und Kopfpunkte. Vor allem bei weißen Tieren fallen die blauen Beine deutlich auf.',
    'Die Tiere gelten als lebhaft und zugleich zutraulich. Besonders junge Ramelsloher können gut fliegen. Ein vertrautes Verhältnis zum Pfleger entsteht durch ruhige, regelmäßige Betreuung.',
    'Bei der Auslaufbegrenzung sollte die Beweglichkeit der Jungtiere berücksichtigt werden. Deckung und Scharrflächen schaffen Beschäftigung. Geschützte Nester und ein trockener Stall sind auch für wintertaugliche Landhühner wichtig.',
    'Als Zweinutzungshuhn wurde die Rasse für Eier und Fleisch gehalten. Die GEH nennt etwa 170 Eier jährlich als Orientierungswert und hebt die Winterlegefähigkeit hervor. Die einzelne Henne kann davon deutlich abweichen.',
    'Der Ort Ramelsloh zeigt die Verbindung zur Rasse sogar im Wappen: Dort steht ein weißer Hahn mit blauen Beinen.',
    [('GEH: Ramelsloher Huhn', 'https://www.g-e-h.de/index.php/rassebeschreibungen/55-gefluegelhuhn/153-ramelsloher-huhn')])

add('araucana', 'Araucana', 'Chile',
    'Schwanzlose Hühner mit besonderen Kopffedern und türkisfarbenen Eiern.',
    ('2–2,5 kg', '1,6–2 kg'), 'Bruteier mindestens 50 g; türkisfarbene Schale.',
    'Araucana gehen auf Hühner der indigenen Bevölkerung Chiles zurück. Ihre ältere Entstehungsgeschichte ist nicht in allen Einzelheiten geklärt. Der deutsche Rassetyp wurde aus diesen Besonderheiten zu einem eigenen Ausstellungshuhn entwickelt.',
    'Der Körper wirkt oval, ein äußerlich sichtbarer Schwanz fehlt. Auf dem Kopf sitzt ein niedriger Erbsenkamm. Auffällig sind Ohrbommeln, ein Bart oder eine Kombination daraus; diese Federmerkmale prägen das Gesicht.',
    'Typische Beispiele sind wildfarbig, goldhalsig, silberhalsig, schwarz und weiß. Die Gefiederfarbe ist von der Eierschalenfarbe zu unterscheiden: Ein türkisfarbenes Ei bedeutet nicht, dass die Henne türkisfarbene Federn trägt.',
    'Araucana sind robuste Landhühner mit aufmerksamer Ausstrahlung. Das Verhalten einzelner Linien kann unterschiedlich ausfallen. Aus der besonderen Körperform allein lässt sich kein bestimmtes Temperament ableiten.',
    'Trockener Stall, geschützte Nester und strukturierter Auslauf bilden die Grundlage. Bei bärtigen Tieren sollten Futter- und Wasserstellen so gestaltet sein, dass die Gesichtsfedern sauber bleiben. Zuchtfragen gehören in erfahrene Hände.',
    'Die ungewöhnliche Eierschalenfarbe ist ein wesentliches Zuchtmerkmal. Daneben zählen Körperform, Vitalität und Kopfbefiederung. Die Großrasse ist ein eigener Eintrag und nicht mit Zwerg-Araucana gleichzusetzen.',
    'Ohrbommeln sind Federbüschel seitlich am Kopf. Ein Bart sitzt dagegen an Wangen und Kehle – beides lässt sich beim genauen Hinsehen unterscheiden.',
    [('Sonderverein: Standard Araucana', 'https://www.sonderverein-araucana.de/das-araucana-huhn/standard/standard-araucana/')])

add('barnevelder', 'Barnevelder', 'Niederlande',
    'Kräftige Hühner mit dunklen Eiern und kunstvoller doppelter Säumung.',
    ('3–3,5 kg', '2,5–2,75 kg'), 'Bruteier mindestens 60 g; dunkelbraune Schale.',
    'Die Rasse entstand im niederländischen Raum Barneveld. Die Zucht verband örtliche Hühner mit weiteren Rassen und richtete besonderes Augenmerk auf braune Eier. Später wurde die doppelte Federzeichnung zu einem bekannten Erkennungsmerkmal.',
    'Barnevelder besitzen einen breiten, tiefen Körper mit gerundeter Brust. Der Rücken steigt zum Schwanz an. Ein Einfachkamm und gelbe, unbefiederte Beine ergänzen den kräftigen, aber nicht plumpen Eindruck.',
    'Besonders bekannt ist braun-schwarzdoppeltgesäumt. Auf den Körperfedern der Henne verlaufen zwei dunkle Linien auf brauner Grundfarbe. Es gibt außerdem andere Farbenschläge, unter anderem schwarz und weiß.',
    'Der Sonderverein beschreibt Barnevelder als zutrauliche Hühner. Ruhiges Verhalten und regelmäßiger Kontakt fördern die Gewöhnung. Die individuelle Persönlichkeit bleibt auch innerhalb einer Rasse unterschiedlich.',
    'Bewegung und Scharrmöglichkeiten ergänzen einen trockenen Stall. Gut zugängliche Nester helfen, die Eier sauber zu halten. Saubere Einstreu ist dabei sinnvoller als häufiges Reinigen verschmutzter Bruteier.',
    'Eier und Fleisch gehörten zur ursprünglichen Nutzung. Heute stehen daneben Federzeichnung und Rasseerhaltung im Mittelpunkt. Die dunkle Schalenfarbe kann zwischen Hennen und im Verlauf einer Legeperiode variieren.',
    'Die doppelte Säumung lässt sich bei Hennen besonders gut studieren. Der Hahn desselben Farbenschlags sieht deshalb nicht wie eine vergrößerte Henne aus.',
    [('Sonderverein: Musterbeschreibung', 'https://www.sv-barnevelder.de/barnevelder-musterbeschreibung'),
     ('Sonderverein: Herauszüchtung', 'https://www.sv-barnevelder.de/herausz%C3%BCchtung'),
     ('Sonderverein: Rasseüberblick', 'https://www.sv-barnevelder.de/')])

add('new-hampshire', 'New Hampshire', 'USA',
    'Früh entwickelte amerikanische Zweinutzungshühner mit warmen Gefiederfarben.',
    ('3–3,5 kg', '2,25–2,7 kg'), 'Bruteier mindestens 58 g laut Sonderverein; braune Schale.',
    'New Hampshire wurden in den USA aus Rhodeländern weiterentwickelt. Die Auswahl richtete sich auf frühe Entwicklung, Wachstum und Nutzleistung. Der Name stammt vom amerikanischen Bundesstaat, nicht von der später gezüchteten deutschen Zwergform.',
    'Der breite, gut gerundete Körper zeigt eine volle Brust und einen ausgeprägten Bauch. Ein Einfachkamm und gelbe, unbefiederte Beine kennzeichnen den Nutztyp. Die Form wirkt kompakt und ausgewogen.',
    'Der Sonderverein nennt goldbraun, weiß und goldbraun-blaugezeichnet für die Großrasse. Bei goldbraunen Tieren entstehen reizvolle Unterschiede zwischen Hals, Körper und dunkleren Schwanzpartien. Die Zwergform besitzt eine eigene Standardgeschichte.',
    'Die Rasse gilt als ruhig und gut handhabbar. Dennoch bleibt sie ein aktives Huhn, das gern scharrt und sucht. Zutraulichkeit braucht verlässlichen Umgang.',
    'Gut erreichbare Sitzplätze, trockene Nester und Beschäftigung im Auslauf passen zum kräftigen Körper. Bei der Fütterung sollte die Körperkondition beobachtet werden. Schnelles Wachstum ersetzt keine ausgewogene Versorgung.',
    'Die Zucht verbindet braune Eier mit einer brauchbaren Fleischleistung. Der Sonderverein nennt für Bruteier mindestens 58 g. Ältere Übersichten führen teils andere Werte; ein Mindestgewicht ist zudem kein Durchschnitt aller gelegten Eier.',
    'New Hampshire und Zwerg-New-Hampshire bleiben zwei getrennte Rassenporträts mit eigenen Seiten und QR-Zielen.',
    [('Sonderverein: Farbenschläge', 'https://www.sv-newhampshire.de/das-new-hampshire-huhn/die-farbschlage/'),
     ('Sonderverein: Brut und Aufzucht', 'https://www.sv-newhampshire.de/das-new-hampshire-huhn/brut-und-aufzucht/'),
     ('Sonderverein: Zuchtziele', 'https://www.sv-newhampshire.de/das-new-hampshire-huhn/aktuelle-zuchtziele/'),
     ('BDRG: Rassetafeln Hühner (PDF)', 'https://www.bdrg.de/media/docs/Rassetafeln_Huehner.pdf')])

add('welsumer', 'Welsumer', 'Niederlande',
    'Niederländische Nutzhühner, deren große braune Eier zur Rasse gehören.',
    ('2,75–3,25 kg laut verlinkter Musterbeschreibung', '2–2,5 kg'),
    'Bruteier mindestens 65 g; dunkelbraune, wenig glänzende Schale.',
    'Welsumer entstanden aus Landhühnern bei Welsum und im Umfeld von Apeldoorn. Große, braune Eier gehörten von Anfang an zum Zuchtinteresse. 1921 wurden Tiere und Eier auf der Weltgeflügelausstellung in Den Haag international vorgestellt.',
    'Der waagerecht getragene Körper ist geräumig und walzenförmig. Breite Brust, voller Bauch und gelbe Beine zeigen den Nutztyp. Ein mittelgroßer Einfachkamm und rote Ohrlappen ergänzen den Kopf.',
    'Rost-rebhuhnfarbig ist besonders bekannt. Daneben werden orangefarbige und perlgrau-orangefarbige Tiere beschrieben. Beim Hahn lohnt der Blick auf die Brust: Die Federzeichnung ist vielschichtiger als eine einheitlich schwarze Fläche.',
    'Der Rassetyp verbindet einen kräftigen Körper mit Beweglichkeit. Als wetterhartes Zwiehuhn wurde er für praktische Haltung entwickelt. Vertrautheit zum Menschen hängt dennoch vom Umgang und von der jeweiligen Linie ab.',
    'Ein gut nutzbarer Auslauf bietet Beschäftigung. Saubere, ausreichend große Nester helfen bei der Gewinnung unbeschädigter Eier. Gerade bei einer auf Eierqualität gezüchteten Rasse lohnt die regelmäßige Beobachtung der einzelnen Hennen.',
    'Welsumer liefern Eier und Fleisch. Das Mindestgewicht von 65 g für Bruteier ist ein Zuchtwert und keine Aussage, dass jedes Ei genau so viel wiegt. Gewichtsangaben der Tiere können je nach Standardfassung abweichen.',
    'In Welsum erinnert seit 1983 ein Denkmal mit Hühnerfiguren an die Rasse und ihre Züchter.',
    [('Sonderverein: Geschichte der Welsumer', 'https://www.sv-welsumer.de/'),
     ('Schweizer Welsumerklub: Musterbeschreibung', 'https://www.welsumerklub.ch/standard.html')])

add('wyandotten', 'Wyandotten', 'USA / deutsche Zucht',
    'Gerundete Zweinutzungshühner mit Rosenkamm und vielfältigen Federzeichnungen.',
    ('3,4–3,8 kg nach der verlinkten Rasseübersicht', '2,5–3 kg'),
    'Bruteier: weißer Farbenschlag mindestens 55 g, andere 53 g; gelbliche bis braune Schale.',
    'Wyandotten wurden 1883 in den USA anerkannt und im selben Jahr nach Deutschland eingeführt. Hier entwickelte sich ein eigener Typ. Der BDRG führte 2018 dafür die Bezeichnung Deutsche Wyandotten ein; dieses Porträt behandelt diesen hierzulande gezüchteten Großrassetyp.',
    'Die volle, gerundete Körperform geht in einen breiten Schwanz über. Auf dem Kopf liegt ein Rosenkamm. Gelbe, unbefiederte Beine und die weichen Übergänge der Körperlinien bestimmen das Erscheinungsbild.',
    'Silber-schwarzgesäumt gehört zu den frühen Farbenschlägen. Schwarze, weiße und zahlreiche weitere Varianten kamen hinzu. Bei gesäumten Tieren zeichnet ein dunkler Rand die einzelne Feder nach.',
    'Wyandotten werden als ruhige, umgängliche Hühner geschätzt. Ihre gelassene Art erleichtert die Beobachtung, bedeutet aber nicht, dass jedes Tier von selbst handzahm wird.',
    'Niedrige, stabile Sitzplätze und gut zugängliche Nester passen zum kräftigen Körper. Bewegungsraum und Scharrmöglichkeiten halten auch gemütliche Tiere beschäftigt. Dichtes Gefieder sollte die regelmäßige Kontrolle der Körperkondition nicht ersetzen.',
    'Die Rasse wurde für Eier und Fleisch genutzt. Schalenfarbe und Bruteier-Mindestgewicht unterscheiden sich teilweise nach Farbenschlag. Die große Form und Deutsche Zwerg-Wyandotten sind getrennte Einträge.',
    'Eine einfache Säumung folgt dem Federrand. Das unterscheidet sie von der doppelten Zeichnung, die man beispielsweise bei Barnevelder-Hennen sieht.',
    [('Landesverband Sachsen-Anhalt: Wyandotten', 'https://www.rassegefluegel-sachsen-anhalt.de/sv-nachrichten/wyandotten/'),
     ('BDRG: Bekanntmachung zur Benennung, Februar 2018', 'https://www.bdrg.de/bza/bekanntmachungungen-des-bza/der-bza-sparte-gefluegel-gibt-bekannt-februar-2018'),
     ('Zootier-Lexikon: Große Haushuhnrassen', 'https://www.zootier-lexikon.org/voegel-aves/huehnervoegel-und-hoatzins/fasanenartige/haushuhn-grosse-rassen')])

add('deutsche-lachshuehner', 'Deutsche Lachshühner', 'Deutschland / Frankreich',
    'Kräftige, zutrauliche Hühner mit Bart, Fußfedern und fünf Zehen.',
    ('3–4 kg', 'etwa 2,5–3 kg laut Geflügelzeitung; andere Übersichten bis 3,25 kg'),
    'Helle Eier; Gewichte unterscheiden sich nach Linie und Legealter.',
    'Aus französischen Faverolles entwickelten deutsche Züchter einen eigenen Zweinutzungstyp. Die französischen Vorfahren waren besonders für den Fleischmarkt gezüchtet worden. In Deutschland rückte die Verbindung von Körperfülle und Eierleistung stärker in den Mittelpunkt.',
    'Ein breiter Körper, Backen- und Kinnbart sowie leicht befiederte Beine fallen sofort auf. An jedem Fuß sitzen fünf Zehen. Die zusätzliche Zehe soll von der hinteren Zehe getrennt erkennbar sein.',
    'Beim lachsfarbigen Farbenschlag unterscheiden sich Hahn und Henne stark. Die Henne wirkt warm lachsfarben und rahmfarben, der Hahn deutlich kontrastreicher. Außerdem gibt es weiß, weiß-schwarzcolumbia und blau-lachsfarbig.',
    'Deutsche Lachshühner gelten als gutmütig und zutraulich. Das macht sie für ruhige Beobachtungen interessant. Vertrauen entsteht durch geduldigen Umgang und passende Haltungsbedingungen.',
    'Tränken und Futterstellen sollten den Bart möglichst sauber halten. Tiefe offene Wasserschalen können die Gesichtsfedern durchnässen. Trockene Einstreu kommt außerdem den leicht befiederten Füßen zugute.',
    'Die Geflügelzeitung nennt etwa 150 Eier jährlich als Rasseorientierung und berichtet von 132 Eiern im Mittel einer geprüften Gruppe. Solche Messergebnisse beschreiben diese Gruppe, nicht jede Henne. Der Sonderverein dokumentiert ergänzend seine Leistungsprüfung.',
    'Der Name „Lachs“ bezieht sich auf einen Farbenschlag. Die Rasse gibt es auch mit ganz anderem Federkleid.',
    [('Geflügelzeitung: Deutsche Lachshühner', 'https://www.gefluegelzeitung.de/gefluegelwissen/deutsche-lachshuehner/'),
     ('Sonderverein: Legeleistungsprüfung', 'https://www.sv-deutscher-lachshuhnzuechter.de/lachsh%C3%BChner/wissenschaft/legeleistungspr%C3%BCfung-2020/'),
     ('Wikipedia: Deutsches Lachshuhn – abweichende Gewichtsobergrenze', 'https://de.wikipedia.org/wiki/Deutsches_Lachshuhn')])

add('seidenhuehner', 'Seidenhühner', 'Ostasien',
    'Haarartig weiche Federn, fünf Zehen und ein ganz eigener Kopfschmuck.',
    ('1,4–1,7 kg', '1,1–1,4 kg'), 'Bruteier mindestens 40 g; hellbraune Schale.',
    'Seidenhühner sind seit langer Zeit in Ostasien bekannt. Ihre auffällige Federstruktur machte sie auch außerhalb ihrer Herkunftsregion berühmt. Die hier vorgestellte Rasse ist die größere Form; daneben bestehen eigenständige Zwerg-Seidenhühner.',
    'Die Federäste bilden keine so fest geschlossene Fläche wie bei gewöhnlichem Hühnergefieder. Dadurch wirkt das Federkleid haarartig. Haube, Walnusskamm, häufig dunkle Haut, türkisfarbene Ohrscheiben und fünf Zehen ergeben ein unverwechselbares Bild.',
    'Es gibt unter anderem weiße, schwarze, blaue und gelbe Tiere sowie Varianten mit und ohne Bart. Nicht jede Farbe zeigt die Hautpigmentierung gleich. Ein heller Vogel ist also keineswegs automatisch ein anderes Huhn.',
    'Seidenhühner gelten als ruhig und können sehr zutraulich werden. Hennen zeigen häufig deutliche Brutlust. Diese Eigenschaft macht sie als Glucken interessant, verringert aber zeitweise die Eierproduktion.',
    'Nester und Sitzplätze sollten niedrig und leicht erreichbar sein. Trockene, geschützte Bereiche sind wegen der besonderen Federn wichtig. Haubenfedern dürfen die Sicht nicht verdecken; saubere Fußbefiederung erleichtert die Pflege.',
    'Heute werden Seidenhühner besonders wegen ihrer Gestalt und ihres Brutverhaltens gehalten. Eine hohe jährliche Eierzahl steht weniger im Vordergrund. Ihre geringe Größe macht die hier behandelte Form nicht automatisch zum Zwerghuhn.',
    'Das weiche Aussehen entsteht durch den Aufbau der Federn. Es handelt sich nicht um Fell, obwohl der erste Eindruck daran erinnert.',
    [('Sonderverein: Seidenhühner', 'https://www.sv-silkiespolands.de/betreute-rassen/seidenh%C3%BChner/')])

add('antwerpener-bartzwerge', 'Antwerpener Bartzwerge', 'Belgien',
    'Belgische Urzwerge mit üppigem Bart und stolz vorgestreckter Brust.',
    ('etwa 700 g', 'etwa 600 g'), 'Bruteier mindestens 28 g; weiße bis cremefarbene Schale.',
    'Die Rasse wurde in der zweiten Hälfte des 19. Jahrhunderts in Belgien geformt. Sie gehört zu den Urzwergen: Es gibt keine entsprechende Großrasse, die lediglich verkleinert wurde. Der Name erinnert an Antwerpen.',
    'Der kurze, breite Körper wird aufgerichtet getragen. Bart, Halskrause und volle Brust betonen die Vorderpartie. Dazu kommen tief getragene Flügel, ein Rosenkamm und unbefiederte Beine. Der Rücken erscheint auffallend kurz.',
    'Wachtelfarbig ist ein bekanntes Beispiel. Daneben bestehen zahlreiche Varianten, etwa schwarz, weiß, perlgrau und gold-porzellanfarbig. Die Farbvielfalt verändert den Eindruck, nicht aber die typische Körperaufteilung.',
    'Der Rassetyp wirkt keck und aufmerksam. Wie zutraulich ein Tier wird, hängt auch von Aufzucht und Umgang ab. Für Besucher lohnt es, Haltung und Bewegung in Ruhe zu beobachten.',
    'Kleine Tiere benötigen ebenso sichere Ausläufe und geschützte Ruheplätze wie große Hühner. Futter- und Wasserstellen sollten zum kleinen Kopf passen und den Bart sauber halten. Bei gemischten Gruppen ist auf ungestörten Zugang zum Futter zu achten.',
    'Im Vordergrund stehen Liebhaberzucht, Ausstellung und die Erhaltung des besonderen Typs. Die kleinen, hellen Eier sind ein zusätzlicher Nutzen. Ein Bruteier-Mindestgewicht von 28 g beschreibt die Zuchtauswahl, nicht jedes gelegte Ei.',
    'Der Körper wirkt vorn voller als hinten. Dieser gewollte Schwerpunkt unterscheidet Antwerpener Bartzwerge von vielen anderen kleinen Hühnern.',
    [('Sonderverein Belgische Bartzwerge: Antwerpener Bartzwerge', 'https://www.belgischebartzwerge.de/die-belgischen-bartzwerge/antwerpener-bartzwerge/')],
    group='Zwerghuhn')
